### ISSUE TITLE
Strange size results

### ISSUE THREAD

**Issue by hemind** [eddieferrer/sizesquirrel-open#726]
size 37 of Men's Katana Lace will give size 37 of Men's Skwama, but size 37.5 of Katana will give size 36.5 of Skwama...  You can find this by these two links.
https://sizesquirrel.com/public_match?want_item_id=323&have_item_id=63&size=37
https://sizesquirrel.com/public_match?want_item_id=323&have_item_id=63&size=37.5

**Comment by eddieferrer** [comment]
This particular issue has to do with the intricacies of the US/EUR size conversion. It happens because some US sizes actually convert to a range of EUR sizes and converting from EUR to US also has some issues, specifically with the size 37.5. You can try putting in your 'have' size in US to see if you get more accurate results.
